from __future__ import annotations

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
LEGACY_DIR = DATA_DIR / "legacy"
DB_PATH = DATA_DIR / "fund_manager_workstation.db"
APP_TITLE = "Fund Manager Workstation v2"
SEED_VERSION = "v2-real"
BUSINESS_DAYS = 756  # ~3 years
DEFAULT_HISTORY_YEARS = 3
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)
HTTP_HEADERS = {"User-Agent": USER_AGENT}

ETF_WATCHLIST: list[dict] = [
    {
        "instrument_id": "etf_icln",
        "ticker": "ICLN",
        "name": "iShares Global Clean Energy ETF",
        "asset_class": "ETF",
        "sub_asset_class": "Equity",
        "category": "Clean Energy ETF",
        "currency": "USD",
        "region": "Global",
        "country": "Global",
        "issuer": "BlackRock iShares",
        "issuer_type": "Fund",
        "rating": "A",
        "duration_years": 0.0,
        "theme": "clean energy",
        "esg_score": 86.0,
        "liquidity_score": 78.0,
        "expense_ratio": 0.40,
        "aum_mn": 0.0,
        "source": "Yahoo Finance",
    },
    {
        "instrument_id": "etf_tan",
        "ticker": "TAN",
        "name": "Invesco Solar ETF",
        "asset_class": "ETF",
        "sub_asset_class": "Equity",
        "category": "Solar ETF",
        "currency": "USD",
        "region": "Global",
        "country": "Global",
        "issuer": "Invesco",
        "issuer_type": "Fund",
        "rating": "A",
        "duration_years": 0.0,
        "theme": "clean energy",
        "esg_score": 82.0,
        "liquidity_score": 72.0,
        "expense_ratio": 0.66,
        "aum_mn": 0.0,
        "source": "Yahoo Finance",
    },
    {
        "instrument_id": "etf_pbw",
        "ticker": "PBW",
        "name": "Invesco WilderHill Clean Energy ETF",
        "asset_class": "ETF",
        "sub_asset_class": "Equity",
        "category": "Clean Energy ETF",
        "currency": "USD",
        "region": "US",
        "country": "United States",
        "issuer": "Invesco",
        "issuer_type": "Fund",
        "rating": "A",
        "duration_years": 0.0,
        "theme": "clean energy",
        "esg_score": 80.0,
        "liquidity_score": 68.0,
        "expense_ratio": 0.62,
        "aum_mn": 0.0,
        "source": "Yahoo Finance",
    },
    {
        "instrument_id": "etf_esgu",
        "ticker": "ESGU",
        "name": "iShares ESG Aware MSCI USA ETF",
        "asset_class": "ETF",
        "sub_asset_class": "Equity",
        "category": "ESG Equity ETF",
        "currency": "USD",
        "region": "US",
        "country": "United States",
        "issuer": "BlackRock iShares",
        "issuer_type": "Fund",
        "rating": "AA",
        "duration_years": 0.0,
        "theme": "esg",
        "esg_score": 90.0,
        "liquidity_score": 89.0,
        "expense_ratio": 0.15,
        "aum_mn": 0.0,
        "source": "Yahoo Finance",
    },
    {
        "instrument_id": "etf_esgd",
        "ticker": "ESGD",
        "name": "iShares ESG Aware MSCI EAFE ETF",
        "asset_class": "ETF",
        "sub_asset_class": "Equity",
        "category": "ESG Equity ETF",
        "currency": "USD",
        "region": "Developed ex-US",
        "country": "Global",
        "issuer": "BlackRock iShares",
        "issuer_type": "Fund",
        "rating": "AA",
        "duration_years": 0.0,
        "theme": "esg",
        "esg_score": 88.0,
        "liquidity_score": 74.0,
        "expense_ratio": 0.20,
        "aum_mn": 0.0,
        "source": "Yahoo Finance",
    },
    {
        "instrument_id": "etf_susl",
        "ticker": "SUSL",
        "name": "iShares ESG MSCI USA Leaders ETF",
        "asset_class": "ETF",
        "sub_asset_class": "Equity",
        "category": "ESG Equity ETF",
        "currency": "USD",
        "region": "US",
        "country": "United States",
        "issuer": "BlackRock iShares",
        "issuer_type": "Fund",
        "rating": "AA",
        "duration_years": 0.0,
        "theme": "esg leaders",
        "esg_score": 92.0,
        "liquidity_score": 82.0,
        "expense_ratio": 0.10,
        "aum_mn": 0.0,
        "source": "Yahoo Finance",
    },
    {
        "instrument_id": "etf_dsi",
        "ticker": "DSI",
        "name": "iShares MSCI KLD 400 Social ETF",
        "asset_class": "ETF",
        "sub_asset_class": "Equity",
        "category": "ESG Equity ETF",
        "currency": "USD",
        "region": "US",
        "country": "United States",
        "issuer": "BlackRock iShares",
        "issuer_type": "Fund",
        "rating": "AA",
        "duration_years": 0.0,
        "theme": "esg",
        "esg_score": 89.0,
        "liquidity_score": 76.0,
        "expense_ratio": 0.25,
        "aum_mn": 0.0,
        "source": "Yahoo Finance",
    },
    {
        "instrument_id": "etf_grnb",
        "ticker": "GRNB",
        "name": "VanEck Green Bond ETF",
        "asset_class": "ETF",
        "sub_asset_class": "Fixed Income",
        "category": "Green Bond ETF",
        "currency": "USD",
        "region": "Global",
        "country": "Global",
        "issuer": "VanEck",
        "issuer_type": "Fund",
        "rating": "AA",
        "duration_years": 6.0,
        "theme": "green",
        "esg_score": 87.0,
        "liquidity_score": 66.0,
        "expense_ratio": 0.20,
        "aum_mn": 0.0,
        "source": "Yahoo Finance",
    },
    {
        "instrument_id": "etf_susb",
        "ticker": "SUSB",
        "name": "iShares ESG USD Corporate Bond ETF",
        "asset_class": "ETF",
        "sub_asset_class": "Fixed Income",
        "category": "ESG Bond ETF",
        "currency": "USD",
        "region": "US",
        "country": "United States",
        "issuer": "BlackRock iShares",
        "issuer_type": "Fund",
        "rating": "AA",
        "duration_years": 5.2,
        "theme": "esg fixed income",
        "esg_score": 85.0,
        "liquidity_score": 79.0,
        "expense_ratio": 0.12,
        "aum_mn": 0.0,
        "source": "Yahoo Finance",
    },
    {
        "instrument_id": "etf_shy",
        "ticker": "SHY",
        "name": "iShares 1-3 Year Treasury Bond ETF",
        "asset_class": "ETF",
        "sub_asset_class": "Fixed Income",
        "category": "Short Treasury ETF",
        "currency": "USD",
        "region": "US",
        "country": "United States",
        "issuer": "BlackRock iShares",
        "issuer_type": "Fund",
        "rating": "AAA",
        "duration_years": 1.8,
        "theme": "treasury",
        "esg_score": 70.0,
        "liquidity_score": 94.0,
        "expense_ratio": 0.15,
        "aum_mn": 0.0,
        "source": "Yahoo Finance",
    },
    {
        "instrument_id": "etf_ief",
        "ticker": "IEF",
        "name": "iShares 7-10 Year Treasury Bond ETF",
        "asset_class": "ETF",
        "sub_asset_class": "Fixed Income",
        "category": "Treasury ETF",
        "currency": "USD",
        "region": "US",
        "country": "United States",
        "issuer": "BlackRock iShares",
        "issuer_type": "Fund",
        "rating": "AAA",
        "duration_years": 7.2,
        "theme": "treasury",
        "esg_score": 70.0,
        "liquidity_score": 92.0,
        "expense_ratio": 0.15,
        "aum_mn": 0.0,
        "source": "Yahoo Finance",
    },
    {
        "instrument_id": "etf_emb",
        "ticker": "EMB",
        "name": "iShares J.P. Morgan USD Emerging Markets Bond ETF",
        "asset_class": "ETF",
        "sub_asset_class": "Fixed Income",
        "category": "EM Sovereign Bond ETF",
        "currency": "USD",
        "region": "EM",
        "country": "Global",
        "issuer": "BlackRock iShares",
        "issuer_type": "Fund",
        "rating": "BBB",
        "duration_years": 6.5,
        "theme": "em sovereign",
        "esg_score": 62.0,
        "liquidity_score": 88.0,
        "expense_ratio": 0.39,
        "aum_mn": 0.0,
        "source": "Yahoo Finance",
    },
]

TEFAS_WATCHLIST: list[dict] = [
    {"instrument_id": "ppf_tp2", "fund_code": "TP2", "asset_class": "TEFAS Fund", "sub_asset_class": "Money Market", "category": "PPF", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AAA", "duration_years": 0.05, "theme": "liquid"},
    {"instrument_id": "ppf_pry", "fund_code": "PRY", "asset_class": "TEFAS Fund", "sub_asset_class": "Money Market", "category": "PPF", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AAA", "duration_years": 0.05, "theme": "liquid"},
    {"instrument_id": "ppf_dly", "fund_code": "DLY", "asset_class": "TEFAS Fund", "sub_asset_class": "Money Market", "category": "PPF", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AAA", "duration_years": 0.05, "theme": "liquid"},
    {"instrument_id": "ppf_zbj", "fund_code": "ZBJ", "asset_class": "TEFAS Fund", "sub_asset_class": "Money Market", "category": "PPF", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AAA", "duration_years": 0.05, "theme": "liquid"},
    {"instrument_id": "ppf_bgp", "fund_code": "BGP", "asset_class": "TEFAS Fund", "sub_asset_class": "Money Market", "category": "PPF", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AAA", "duration_years": 0.05, "theme": "liquid"},
    {"instrument_id": "ppf_hsl", "fund_code": "HSL", "asset_class": "TEFAS Fund", "sub_asset_class": "Money Market", "category": "PPF", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AAA", "duration_years": 0.05, "theme": "liquid"},
    {"instrument_id": "ppf_ppn", "fund_code": "PPN", "asset_class": "TEFAS Fund", "sub_asset_class": "Money Market", "category": "PPF", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AAA", "duration_years": 0.05, "theme": "liquid"},
    {"instrument_id": "ppf_ioo", "fund_code": "IOO", "asset_class": "TEFAS Fund", "sub_asset_class": "Money Market", "category": "PPF", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AAA", "duration_years": 0.05, "theme": "liquid"},
    {"instrument_id": "ppf_ppz", "fund_code": "PPZ", "asset_class": "TEFAS Fund", "sub_asset_class": "Money Market", "category": "PPF", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AAA", "duration_years": 0.05, "theme": "liquid"},
    {"instrument_id": "ppf_fil", "fund_code": "FIL", "asset_class": "TEFAS Fund", "sub_asset_class": "Money Market", "category": "PPF", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AAA", "duration_years": 0.05, "theme": "liquid"},
    {"instrument_id": "kvbaf_gbl", "fund_code": "GBL", "asset_class": "TEFAS Fund", "sub_asset_class": "Short Term Debt", "category": "KVBAF", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AA", "duration_years": 0.70, "theme": "short duration"},
    {"instrument_id": "kvbaf_hpt", "fund_code": "HPT", "asset_class": "TEFAS Fund", "sub_asset_class": "Short Term Debt", "category": "KVBAF", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AA", "duration_years": 0.70, "theme": "short duration"},
    {"instrument_id": "kvbaf_ist", "fund_code": "IST", "asset_class": "TEFAS Fund", "sub_asset_class": "Short Term Debt", "category": "KVBAF", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AA", "duration_years": 0.70, "theme": "short duration"},
    {"instrument_id": "kvbaf_yht", "fund_code": "YHT", "asset_class": "TEFAS Fund", "sub_asset_class": "Short Term Debt", "category": "KVBAF", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AA", "duration_years": 0.70, "theme": "short duration"},
    {"instrument_id": "kat_ais", "fund_code": "AIS", "asset_class": "TEFAS Fund", "sub_asset_class": "Participation MM", "category": "Katılım", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AA", "duration_years": 0.05, "theme": "katilim"},
    {"instrument_id": "kat_klu", "fund_code": "KLU", "asset_class": "TEFAS Fund", "sub_asset_class": "Participation MM", "category": "Katılım", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AA", "duration_years": 0.05, "theme": "katilim"},
    {"instrument_id": "kat_ppg", "fund_code": "PPG", "asset_class": "TEFAS Fund", "sub_asset_class": "Participation MM", "category": "Katılım", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AA", "duration_years": 0.05, "theme": "katilim"},
    {"instrument_id": "kat_tlk", "fund_code": "TLK", "asset_class": "TEFAS Fund", "sub_asset_class": "Participation MM", "category": "Katılım", "currency": "TRY", "region": "Turkey", "country": "Turkey", "issuer": "TEFAS", "issuer_type": "Fund", "rating": "AA", "duration_years": 0.05, "theme": "katilim"},
]

PUBLIC_MARKET_INSTRUMENTS: list[dict] = [
    {
        "instrument_id": "repo_on",
        "name": "BIST Repo O/N",
        "asset_class": "TL Money Market",
        "sub_asset_class": "Repo",
        "category": "Repo",
        "currency": "TRY",
        "region": "Turkey",
        "country": "Turkey",
        "issuer": "Borsa Istanbul",
        "issuer_type": "Market",
        "rating": "AAA",
        "duration_years": 1.0 / 365.0,
        "theme": "liquid",
        "source": "Borsa Istanbul Public",
    },
    {
        "instrument_id": "tpp_on",
        "name": "Takasbank Para Piyasası O/N",
        "asset_class": "TL Money Market",
        "sub_asset_class": "TPP",
        "category": "TPP",
        "currency": "TRY",
        "region": "Turkey",
        "country": "Turkey",
        "issuer": "Takasbank",
        "issuer_type": "Market",
        "rating": "AAA",
        "duration_years": 1.0 / 365.0,
        "theme": "liquid",
        "source": "Takasbank Public",
    },
]
